FROM mongo:latest

# custom label for the docker image
LABEL version="0.1" maintainer="ObjectRocket"


RUN apt-get update -y
RUN apt-get remove mongodb-org -y
RUN apt-get install mongodb -y
RUN mkdir -p ./data/db
RUN service mongodb start -y


EXPOSE 27017